version: '3.9'

services:
  icecast:
    build: .
    container_name: icecast-server
    restart: always
    ports:
      - "4500:4500"
    volumes:
      - ./icecast.xml:/etc/icecast2/icecast.xml  # Configuration file
      - ./xslt:/usr/share/icecast2/xslt         # XSLT directory for styling
      - ./log:/var/log/icecast2                 # Persistent log directory
      - /etc/mime.types:/etc/mime.types         # MIME types

    user: "10001:10001"  # Match UID/GID as defined in the Dockerfile